export default {
    INSTALL_APP: 'InstallApp', 
    DASHBOARD: 'Dashboard',
    PRICING: 'Pricing',
    APP_DIRECTORY: 'AppDirectory',
    GENERAL_SETTINGS: 'GeneralSettings',
    THEME_SETTINGS: 'ThemeSettings',
    ORDERS: 'Orders',
    ADD_PRODUCT: 'AddProduct',
    UPDATE_PRODUCT: 'UpdateProduct',
    LIST_PRODUCTS: 'ListProducts',
    CUSTOMERS: 'Customers',
    LIST_CUSTOMERS: 'ListCustomers',
    ADD_CUSTOMER: 'AddCustomer',
    UPDATE_CUSTOMER: 'UpdateCustomer',
    LIST_COLLECTIONS: 'ListCollections',
    ADD_COLLECTION: 'AddCollection',
    UPDATE_COLLECTION: 'UpdateCollection',
    CHOOSE_PLAN: 'ChoosePlan',
    UPDATE_APP: 'UpdateApp',
    FUNCTION_TABLE: 'FunctionTable',
    FUNCTION_SETTINGS: 'FunctionSettings',
    FUNCTION_CREATE: 'FunctionCreate',
    ACCOUNT_SETTINGS: 'AccountSettings',
    ERROR_404: 'Error404',
    ERROR_500: 'Error500',
    PAGE_NOT_FOUND: 'PageNotFound'
}